name: trabecular_bone_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.1
  - matplotlib=3.1.1
  - numpy=1.18.1
  - tensorflow-gpu=1.12
  - scipy=1.4.1
  - pydicom
  - pandas=1.0.3
  - scikit-image=0.16.2
  - cudatoolkit=9.0
  - cuDNN=7.1.4
  - tk=8.6
  
