name: trabecular_bone_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.1
  - matplotlib=3.1.3
  - numpy<1.17 
  - tensorflow-gpu=1.12
  - scipy=1.4.1
  - pydicom=1.4.1
  - pandas=1.0.3
  - scikit-image=0.16.2
  - cudatoolkit=9.2
  - cudnn=7.6.5
  - tk=8.6.10
  - tqdm=4.45.0
  
